### ISSUE TITLE
bug: rank set-background sends rank of user

### ISSUE THREAD

**Issue by Jo3-L** [yagpdb-cc/yagpdb-cc#118]
**Describe the bug in as much detail as possible:**
When using `rank set-background`, it sets the background but also sends the rank card of the user.

**To Reproduce:**

1. Write `-rank set-background https://www.totally.valid.url.com`
2. See output

**Expected behavior:**
Sets background and does not send rank card of user.

**Screenshots:**
![image](https://user-images.githubusercontent.com/56809242/101374392-f8f9c100-3862-11eb-90e5-8c0f1a7a614c.png)

**Additional context:**
n/a

**Comment by JordiHakimZiyech** [comment]
this exact code on the official YAGPDB bot does not do this. https://gyazo.com/0d73d5056e7baa434ac79226adb4ffe7

**Comment by Jo3-L** [comment]
can repro with current code. reopening
