### ISSUE TITLE
bug: avatar command

### ISSUE THREAD

**Issue by soudblox** [yagpdb-cc/yagpdb-cc#120]
**To Reproduce:**

1. Write '-avatar @someone'
2. It will give your avatar instead of the user that you mention
3. See error

Expected result: give the avatar of the user that is mentioned
Actual result: gives your avatar

**Screenshots:**

![image](https://user-images.githubusercontent.com/73058244/101727143-81d45f00-3ae6-11eb-97a5-c0e82652d6ad.png)

**Comment by JordiHakimZiyech** [comment]
https://gyazo.com/387a6bd20423e3e8498eb59bab4b2a3e cant reproduce

**Comment by soudblox** [comment]
wadafaq

**Comment by Jo3-L** [comment]
can't repro.
