### ISSUE TITLE
bug: Suggestion CC possible regex error with prefix `+`

### ISSUE THREAD

**Issue by EsenDR** [yagpdb-cc/yagpdb-cc#127]
**Describe the bug in as much detail as possible:**
Prefix of the server is + and whenever the suggestion cc is set with that regex (the cc regex to match server prefix) it fails and errors to "Did not set regex to match Server Prefix" which it shouldn't. Reach out to <@676260964064165908> on discord (ღRuniRiotღ#6782) if you have a fix for this.

**To Reproduce:**
1. Set prefix to + and bring the suggestions cc and change the - to +
2. Try to run with `+suggest testing for science` or something
3. And find that it defaults to "Did not set regex to match Server Prefix"

**Expected behavior:**
It should just send the suggestion, but it does not. 

**Screenshots:**
Error with + prefix
![error](https://user-images.githubusercontent.com/52873478/102443781-6a144380-3fdc-11eb-819b-b51242e9ef92.jpg)
Works with prefix of -
![worksfine](https://user-images.githubusercontent.com/52873478/102443799-73051500-3fdc-11eb-9ab6-e897b35e60f9.jpg)

**Comment by soudblox** [comment]
happened to me once, if my server prefix is ? and the regex is - then it will error that

**Comment by EsenDR** [comment]
> happened to me once, if my server prefix is ? and the regex is - then it will error that

You should probably reread the issue. The problem occurs when when both, server AND CC prefix is set to `+`

**Comment by alikuxac** [comment]
What is your regex for suggest command?

**Comment by DaviiD1337** [comment]
Fixed in #131
