### ISSUE TITLE
bug: AFK requires too many arguments

### ISSUE THREAD

**Issue by LRitzdorf** [yagpdb-cc/yagpdb-cc#135]
**Describe the bug in as much detail as possible:**

The main AFK command (`afk.go.tmpl`, under `afk`) requires at least a three-word reason in order to work properly. If anything less is given, like `-afk Testing`, an inappropriate error message is returned (see screenshot below for example).

**To Reproduce:**

1. Add the AFK command as described in the informative header block.
2. Run `-afk one-word-reason-for-testing` (or use a similar one-word argument).
3. The error message returned does not match the situation.

**Expected behavior:**

The command should set the user's AFK status properly.

**Screenshots:**

![unknown.png](https://user-images.githubusercontent.com/42657792/103187095-4b396b00-4880-11eb-9e97-cb806fce9178.png)

**Additional context:**

A resolution was achieved by setting the number to which arguments are compared (line 21) to 2 instead of 4.

**Comment by WickedWizard3588** [comment]
As you stated, here is the same resolution I found

![image](https://user-images.githubusercontent.com/67627239/103307137-60a3c600-4a35-11eb-86a5-b2ee7e1f9363.png)
https://github.com/yagpdb-cc/yagpdb-cc/blob/e3bf21dee55a145ea62a32cb67a49ca04ce345a9/afk/afk.go.tmpl#L21

Hey yes, I have seen that too. To just fix it, change the `4` to `2` and it fixes, and you can set an afk with one word.

I'll attach a GIF here, but my `.*` Trigger is a bit messy, sorry for that. Also, the dash is a bit laggy for me, it saves it, sorry for that mistake in the GIF.

Until someone makes a PR or we make or Joe edits, most probably it'll stay like that. 

https://i.imgur.com/qrFHNIk.gif

**Comment by DaviiD1337** [comment]
ill fix tomorrow

**Comment by DaviiD1337** [comment]
Ok I updated something
