### ISSUE TITLE
Bug: Giveaway ending time bug

### ISSUE THREAD

**Issue by undermaster141** [yagpdb-cc/yagpdb-cc#136]
**Describe the bug in as much detail as possible:**

If you host a long giveaway, the giveaway ending time will display the current time but this isn't the case for short giveaway

**To Reproduce:**

1. Host a long giveaway (eg: 8d)
2. See the footer, it doesn't display the correct ending time
3. Host a short giveaway (eg: 5m)

**Expected behavior:**

The ending time should display, instead, it shows the time you hosted the giveaway

**Screenshots:**

![20201228_164058.jpg](https://user-images.githubusercontent.com/50463132/103201955-2d294480-492c-11eb-873b-1bd2f812658e.jpg)![20201228_164126.jpg](https://user-images.githubusercontent.com/50463132/103201963-31edf880-492c-11eb-9a33-fd23c7855769.jpg)

**Comment by TheHDCrafter** [comment]
Blame Discord for that visual issue. It is a bug on mobile that it displays the timestamps wrong. 
![image](https://user-images.githubusercontent.com/29355595/103456459-d9857500-4cf6-11eb-93be-e8014a7ae563.png)
![Screenshot_20210102-123359](https://user-images.githubusercontent.com/29355595/103456464-e6a26400-4cf6-11eb-9218-6126dc139907.jpg)
