### ISSUE TITLE
request: Allow year in birthday command to be optional somehow

### ISSUE THREAD

**Issue by ShadowNight573** [yagpdb-cc/yagpdb-cc#139]
This originally came up in the help channels with a user asking if they could not specify their birth year just because they weren't comfortable doing so. 

I considered the fact that since the underage user filter is optional and you don't need the year to check if its the users birthday that perhaps a setting to make the year optional would help.
 
Since the command uses newDate to turn the date provided into time.Time. Maybe a default year (just a placeholder) could work?

**Comment by ShadowNight573** [comment]
Could try and PR it myself but I'd rather take input on the idea first.

**Comment by Jo3-L** [comment]
Sounds good to me; for the default year idea, note that it needs to be a leap year to ensure February 29 is allowed.
