### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by AverytheFurry** [yagpdb-cc/yagpdb-cc#141]
**Describe the bug in as much detail as possible:**

Using the suggestion command & setting the regex trigger to
`(?i)\A(\-\s?|<@!?204255221017214977>\s*)((del(ete)?|edit)?suggest(ion)?|(sa|suggestadmin)\s+((?:mark)?dupe|deny|implement(ed)?|archive|approved?|comment))(\s+|\z)` (the default)
Returns an error when I try to run the command. `Error: Did not set regex to match Server Prefix - Syntax: Prefix/Yag Mention <Command> <Args>`

**To Reproduce:**

1. Copy the suggestion code
2. Copy the regex trigger in the code/on the readme page
3. Run the command, `suggest x`
4. See error, even though my prefix is `-`

**Expected behavior:**

The command runs without erroring

**Screenshots:**

![image](https://user-images.githubusercontent.com/47131867/103445448-0408fc80-4c29-11eb-8bae-3b35564e6cc3.png)

**Comment by DaviiD1337** [comment]
ill fix tomorrow 😉

**Comment by Olde7325** [comment]
This is __not a bug__, but intended behaviour.
You see the hyphen in the regex trigger?
`(?i)\A(\-\s?|<@!?204255221017214977>\s*)((del(ete)?|edit)?suggest(ion)?|(sa|suggestadmin)\s+((?:mark)?dupe|deny|implement(ed)?|archive|approved?|comment))(\s+|\z)`
Around `(\-\s?`; You are supposed to change this to the prefix you gave YAGPDB in your server.

**Comment by AverytheFurry** [comment]
> 
> 
> This is **not a bug**, but intended behaviour.
> You see the hyphen in the regex trigger?
> `(?i)\A(\-\s?|<@!?204255221017214977>\s*)((del(ete)?|edit)?suggest(ion)?|(sa|suggestadmin)\s+((?:mark)?dupe|deny|implement(ed)?|archive|approved?|comment))(\s+|\z)`
> Around `(\-\s?`; You are supposed to change the hyphen `-` to the prefix you gave YAGPDB in your server.

That is the prefix I gave YAGPDB in my server.

**Comment by Olde7325** [comment]
Hacky workaround, but it works: remove the `\` preceding the hyphen. That is what throws the error.

**Comment by AverytheFurry** [comment]
> 
> 
> Hacky workaround, but it works: remove the `\` preceding the hyphen. That is what throws the error.
> 
> Edit: found a fix, will PR it soon-ish.

should I still remove the hyphen?

**Comment by Olde7325** [comment]
Up to you to be fair; I am working on a fix currently, however I can't really say how long it'll take.
