### ISSUE TITLE
bug: Suggestion Emoji Issue

### ISSUE THREAD

**Issue by AverytheFurry** [yagpdb-cc/yagpdb-cc#146]
**Describe the bug in as much detail as possible:**
Using the unicode characters (as told to in the readme) returns this error: `Failed executing template: template: CC #16:42:5: executing "CC #16" at <addMessageReactions ...>: error calling addMessageReactions: HTTP 400 Bad Request, {"emoji_id": ["Value \"\ud83d\udc4d\" is not snowflake."]}`
**To Reproduce:**
1. Implement command
2. Set upvote and downvote variables to `👍 & 👎`
3. Command returns error

**Expected behavior:**
No error
**Screenshots:**
![image](https://user-images.githubusercontent.com/47131867/103449198-b062d700-4c59-11eb-8975-95aaa27070b1.png)

![image](https://user-images.githubusercontent.com/47131867/103449133-9d9bd280-4c58-11eb-8ff6-9aeca6751a28.png)

![image](https://user-images.githubusercontent.com/47131867/103449107-5a416400-4c58-11eb-8f64-c9075501aee2.png)

**Comment by Olde7325** [comment]
You are using unicode emoji, these suffice when put as plain text.
In your case like this:
```
{{$Upvote:="👍"}}
{{$Downvote:="👎"}}
```

**Comment by AverytheFurry** [comment]
> 
> 
> You are using unicode emoji, these suffice when put as plain text.
> In your case like this:
> 
> ```
> {{$Upvote:="👍"}}
> {{$Downvote:="👎"}}
> ```

Ah, alright, I'll try this - Maybe the readme could be updated to be a bit more clear?
Thank you <3

**Comment by jo3-l2** [comment]
What Olde said is correct and is noted on the doc page. Please consider first contacting the support server or open a discussion (`Discussions` tab on GitHub) before opening an issue in the future.

Cheers!

**Comment by Olde7325** [comment]
I'll maybe take a look into making the readme a bit more clear. Just as Joe said, please contact [the support server](https://discord.com/invite/0vYlUK2XBKldPSMY) first.
