### ISSUE TITLE
bug: Channel types not displaying correctly (channel-info cc)

### ISSUE THREAD

**Issue by Piterxyz** [yagpdb-cc/yagpdb-cc#151]
**Describe the bug in as much detail as possible:**
Channel types not displaying correctly (channel-info cc)

**To Reproduce:**
Compare this to the image I've sent you below.
```
{{$types := cslice "Text" "DM" "Voice" "Category" "News" "Store"}}
```
**Expected behavior:**
```
{{$types := cslice "Text" "DM" "Voice" "Group DM" "Category" "News" "Store"}}
```
**Screenshots:**
https://i.imgur.com/HTM9cNp.png

**Comment by jo3-l** [comment]
fixed by https://github.com/yagpdb-cc/yagpdb-cc/commit/8dabbaee6b4270ca0761e55fd3bb0a8919a415ca
