### ISSUE TITLE
bug: rank card will load weird

### ISSUE THREAD

**Issue by soudblox** [yagpdb-cc/yagpdb-cc#153]
**Describe the bug in as much detail as possible:**

If you set someone's level to 1,000,000 or above the image will load but the xp bar will be invisible, well no one can even reach that level but eh who cares

**To Reproduce:**

1. set someone level to 1,000,000 or above using the setlevel command
2. xp bar wont load

**Expected behavior:**

load normally

**Screenshots:**

![image](https://user-images.githubusercontent.com/73058244/104302044-ea09cc80-54fa-11eb-9563-b27d48cf0b83.png)

**Additional context:**

the link will be https://vacefron.nl/api/rankcard?username=blox&avatar=https://cdn.discordapp.com/avatars/748529326621982732/d617c84d8a2f1b95226c14abdd30767f.png?size=256&level=2.1161257e+08&rank=1&currentxp=4.219285504e+10&nextlevelxp=42322514100&previouslevelxp=0&custombg=https://xbox-store-checker.com/assets/upload/game/2020/06/optimize/9n5qmw0x81jm-background.jpg&xpcolor=%3Cnil%3E 

so its the &level= part thing

**Comment by soudblox** [comment]
dont mind the shitty screenshot : )

**Comment by jo3-l** [comment]
not a bug, level is way too high.
