### ISSUE TITLE
bug: rank card bug

### ISSUE THREAD

**Issue by soudblox** [yagpdb-cc/yagpdb-cc#154]
**Describe the bug in as much detail as possible:**

if you enable rank card and you do -rank @user it won't do anything

**To Reproduce:**

1. enable rank card
2. do -rank @user
3. it wont send anything

**Screenshots:**
![image](https://user-images.githubusercontent.com/73058244/104337178-c610b000-5527-11eb-8b6d-59bb54938f1f.png)

**Comment by Olde7325** [comment]
Looks like this happens with untracked/unranked users.
WIll look into it, implementing a fallback!

**Comment by soudblox** [comment]
i fixed it by removing with .CmdArgs whiich is required for set-color and set bg

**Comment by soudblox** [comment]
i can make a separate command for them so idrc tbh lol

**Comment by Olde7325** [comment]
Can you share a screenshot where you `-rank @user` with a ranked user? Just to confirm it only happens with unranked users.

**Comment by JordiHakimZiyech** [comment]
found the bug. pushing fix now

**Comment by Olde7325** [comment]
Okay, thanks Jordi!
