### ISSUE TITLE
bug:An error caused the execution of the custom command template to stop

### ISSUE THREAD

**Issue by azcraze** [yagpdb-cc/yagpdb-cc#173]
**Describe the bug in as much detail as possible:**

I get this response when using the caution emoji "to get background info":

> An error caused the execution of the custom command template to stop:

> `Failed executing template: template: CC #10:42:17: executing "edit" at <sdict "name" "Status...>: error calling sdict: invalid dict call
`

**To Reproduce:**

click the caution emoji reaction underneath the embed

**Expected behavior:**
I believe i should see background info if any and something that says there is none if none

**Screenshots:**

![CleanShot 2021-03-21 at 21 35 36](https://user-images.githubusercontent.com/15200975/111933406-684f9580-8a8d-11eb-98c9-40a7662cdff6.png)

**Additional context:**

**Comment by azcraze** [comment]
i also get the same error after clicking on the shield emoji reaction

**Comment by l-zeuch** [comment]
Did you do `-ru dbSetup` as [the documentation](./moderation/report system) says?

**Comment by l-zeuch** [comment]
I found the error, I'll PR a fix once I am back home.
