### ISSUE TITLE
bug: Giveaway CC will not work anymore because of a change on the Discord API

### ISSUE THREAD

**Issue by Pedro-Pessoa** [yagpdb-cc/yagpdb-cc#179]
**Discord API changed**
Looks like something changed on the discord API.
We were using `{{with sendMessageNoEscapeRetID $chan cembed}}` to test if the `$chan` variable was a valid channel.
But, discord is not allowing null/empty messages anymore, so this will always error out.

**To Reproduce:**
Use the `sendMessage` function with a null or empty value

**Additional context:**
A solution that I thought of would be to manually parse and check if the channel is valid using the `getChannel` function.

**Comment by jo3-l** [comment]
Seems like a relatively easy fix. PR appreciated!

**Comment by dvoraknt** [comment]
an easier solution than having to rewrite parts of this massive command is to just add a description to the cembed with a U+2800. I can PR that if you want, working fine for me so far. Need to trim out some of the notation but that can be done with little lost value

**Comment by l-zeuch** [comment]
> An easier solution than having to rewrite parts of this massive command is to just add a description to the cembed with a U+2800.

Sounds rather hacky to me.
Not so sure how to feel about it - I mean it would work, then, however I think this might not be good practise.
After all, this is an official source and we should showcase good code, at least in my opinion.

**Comment by dvoraknt** [comment]
fair enough, based on the number of people that were immediately reporting it on discord I wasn't sure if a quick fix was better in the short term as it seems to be a popular command. Doesn't mean a more proper solution couldn't be done afterwards

**Comment by l-zeuch** [comment]
I'd prefer a rather large change now, which would only had to be done once, than one small change now and postponing the large change.
We'd have to do it either way, in the long run.
Perhaps we could combine this update with a rework of the documentation for the giveaway command, if needed?

**Comment by l-zeuch** [comment]
Yeah, I just took a small glimpse - documentation is, in my opinion, definitely needed. I'd be down writing it, unless somebody else strongly says they want to do it.

**Comment by jo3-l** [comment]
Please open a new issue to track documentation changes @l-zeuch : ) I'd prefer to keep them separate, considering the bugfix is a more critical issue.

**Comment by l-zeuch** [comment]
Fair enough :^)
Was kinda related, so I thought why not in one.
Will open a new one tomorrow morning 👍

**Comment by Satty9361** [comment]
Will try to resolve the bugs this weekend if I hopefully have time.

**Comment by Satty9361** [comment]
Pushed some fixes. Simple enough with @Pedro-Pessoa  pointing out the issue. Let me know if any other issues pop up!!
