### ISSUE TITLE
Formatting trigger in code

### ISSUE THREAD

**Issue by BlackWolfWoof** [yagpdb-cc/yagpdb-cc#194]
![Screenshot_20210425-214622.jpg](https://user-images.githubusercontent.com/29355595/116007367-caad3000-a60f-11eb-81e7-12056ac8b683.jpg) i have seen several users copy the trigger with ` so maybe removing that or using a more elegant way mighz be better.
In this example i used the -be cc

**Comment by l-zeuch** [comment]
Yeah sounds fair to me tbh, would require us to change basically every file though 🤔

**Comment by BlackWolfWoof** [comment]
Yea thsts why i didn't pr xd

**Comment by jo3-l** [comment]
This would probably be solved by having a website for documentation / using markdown for the command descriptions, which is being worked on.

Removing the \` works as a band-aid solution. Happy to accept a PR.

**Comment by l-zeuch** [comment]
I'll speak to Esen, so we document that appropiately then. Appreciate any feedback regarding additional information to be included in the website!
