### ISSUE TITLE
proposal: remove instructions in leading comments completely

### ISSUE THREAD

**Issue by jo3-l** [yagpdb-cc/yagpdb-cc#222]
Now that we have the website and associated infra set up (we have a job making sure the website builds and a job automatically deploying the website on new commits to `master`), I propose that instructions be removed from leading comments completely. All that would be left would be 1) a link to the associated page on the website and 2) information about the author of the CC.

**Motivation**
I think it goes without saying that the website is a far better place to browse and view custom commands than this GitHub repository. The question arises as to why exactly we need to keep instructions in leading comments anymore. Personally, I don't see any benefit of doing so, but I do see several downsides. In particular, if we want to keep the website up to date with the code here, we currently need to change up to 4 things in a single PR:
1) We need to change the actual code.
2) We need to change the instructions in the leading comment.
3) We need to change the code on the website. 
4) We need to change the instructions on the website.

Only 2 of those 4 things are really necessary, the rest is just repetitive work. If we remove the need to keep instructions in header comment, that's only 3 things to change at max, rather than 4. To me, that outweighs any benefit keeping instructions in leading comments could bring.

What do we think of this?

**Comment by l-zeuch** [comment]
+1 on this.
We could also consider changing the branching model a tiny bit - suppose we have loads of PRs being merged (whenever that will be the case): Merge those into a staging branch and then deploy with one commit, rather than sort of spamming the CI/CD...

**Comment by jo3-l** [comment]
Yes, perhaps it's time to switch to a `dev -> main` branching model : )

**Comment by l-zeuch** [comment]
![perhaps](https://user-images.githubusercontent.com/71897876/124402374-2e4e8a80-dd30-11eb-90f6-745235e8aee8.png)

**Comment by EsenDR** [comment]
> Yes, perhaps it's time to switch to a `dev -> main` branching model : )
I like this idea.

In terms of this:
1. We need to change the actual code.
2. We need to change the instructions in the leading comment.
3. We need to change the code on the website.
4. We need to change the instructions on the website.

Feel free to lmk if you guys would like help! More than willing to help out with whatever you guys need.
