### ISSUE TITLE
tracking issue for setting up Prettier

### ISSUE THREAD

**Issue by jo3-l** [yagpdb-cc/yagpdb-cc#223]
Now that we have a few files that aren't just Markdown/custom command code, I think it's a good time to set up a code formatter. I like [Prettier](https://prettier.io/) quite a bit and have used it with success on many of my personal projects; I think we could set it up here as well. However, I think it would be unreasonable to demand that all contributors use it (given that many contributors are pretty new to coding). Instead, I think we should set up a CI workflow that runs after commits and cleans up code automatically.

**Comment by l-zeuch** [comment]
Running it as CI/CD workflow sounds good to me, this also ensures that the format is the same across all files.
Misconfiguration can always happen and it would be definitely out of scope of this project to write specifications on formatting custom command code.
It's meant as a collection, not some code-base for software like yagpdb, VSCode, or the Linux kernel.
I also feel like demanding specific formatting out of the box (before even PRing) could/will discourage a lot of future contributors, as writing a custom command is time intense enough already.
As guidelines for the interested, what is generally seen as good and readable code, sure, but not as a requirement. A workflow can definitely take care of that part.

**Comment by jo3-l** [comment]
Implemented in https://github.com/yagpdb-cc/yagpdb-cc/commit/254d34e867057133d12a20cc98375209bbddfcea.
