### ISSUE TITLE
tracking issue for setting up search for the website

### ISSUE THREAD

**Issue by jo3-l** [yagpdb-cc/yagpdb-cc#229]
All of the local search plugins I've played around with are broken in subtle ways. In particular, the last one broke when `trailingSlash` was set in the Docusaurus options (which prevents relative links from breaking).

I'm not keen on spending any more time trying out local search plugins, so let's just apply for Algolia DocSearch instead and [use the official search plugin](https://docusaurus.io/docs/search#using-algolia-docsearch).

**Comment by l-zeuch** [comment]
I'd like to work on this.

Their [checklist](https://docsearch.algolia.com/docs/who-can-apply/) says something about adding a snippet to the frontend of the website source, but I'm unsure where exactly that is located.

Any pointer with regards to the general structure of the website is appreciated, the rest I can probably figure out on my own.

**Comment by jo3-l** [comment]
See https://docusaurus.io/docs/search.

**Comment by l-zeuch** [comment]
Update on the application: Support already contacted me and asked me to verify by replying to their email -- no we have to wait for a while.
