### ISSUE TITLE
request: leveling: remove members who left the server

### ISSUE THREAD

**Issue by TheCoolestStoryBro** [yagpdb-cc/yagpdb-cc#230]
**Describe the bug in as much detail as possible:**

When running the `!lb` command, it still shows the xp and levels of thoes who left the server!

**To Reproduce:**

1. Have someone leave your server who **has xp**
2. Run `!lb`
3. See blank name 

**Expected behavior:**
For members who left to automatically be removed from the leaderboard and to not come up with blank names 

**Screenshots:**
![Leaderboard](https://user-images.githubusercontent.com/77266761/126252295-486bf354-8af6-4624-8912-6c9c1d468f11.jpg)
(I set my prefix to `!`)

**Comment by LemmeCry** [comment]
You can simply use dbDel in the leave message (Notifications and Feeds > General > Leave message) to do this.
```
{{dbDel .User.ID "xp"}}
```
That will delete the database entry of the person leaving.

**Comment by jo3-l** [comment]
This is, unfortunately, not trivial to do without simply removing the entries connected to those users. `dbTopEntries` does not provide a mechanism to filter out users who are no longer in the server, meaning that we would have to filter the resulting entries manually, which is less than optimal. In a worst-case scenario, we would actually be unable to show any members (say we retrieve 100 entries, and all are connected to users that aren't in the server anymore).

We can certainly improve how unknown members are displayed, though. Perhaps simply displaying their ID (like `toprep` does) would be sufficient.
