### ISSUE TITLE
bug: report system reaction handler errors on any reaction

### ISSUE THREAD

**Issue by spokrr** [yagpdb-cc/yagpdb-cc#244]
### Expected behaviour

reaction menu to proceed

### Actual behaviour

![image](https://user-images.githubusercontent.com/69011306/147762324-3b771e7e-5e2c-4265-9399-8cd2cbb3bd8b.png)
every time anyone reacted anywhere in the server it would post an error message in the announcement channel

### Steps to reproduce.

1. add custom report system
2. react to a message

### Additional context

the commands were unedited

### Terms

- [X] I agree to follow this project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by l-zeuch** [comment]
This is expected behaviour (somewhat), as the reaction handler has to be limited to **only** the report-log channel.

**Comment by spokrr** [comment]
I see how that could be common sense but at the same time just for the sake of clarity I think it'd be good if that was in the https://yagpdb-cc.github.io/moderation/report-system/reaction-handler page under 
![image](https://user-images.githubusercontent.com/69011306/147763286-8ccbb4c6-ee8c-432f-9647-d078afa70442.png)

**Comment by l-zeuch** [comment]
Definitely agree.
If you want to, open a PR and I'll merge it -- I'm currently busy with private things, but this came up often enough to be on my to-do list.

**Comment by spokrr** [comment]
done! #245
