### ISSUE TITLE
request: leveling: add counter between levels

### ISSUE THREAD

**Issue by dskarasev** [yagpdb-cc/yagpdb-cc#261]
### Description

Hi!

I would suggest to add to leveling command an option to calculating the level between two adjacent levels that are not in order. 

Now the script works so that when you reach level 21 you will get a message about reaching an empty level (no role)

For example
Level 20 - Marquis
Level 21 - 
Level 22 - 
e.t.c
Level 30 - Count

### Solution

I suggest instead to take the name of an existing lower level role and add a step counter to the next role. That is, in the above example:

Level 20 - Marquis.
Level 21 - Marquis [2 lvl]
Level 22 - Marquis [3 lvl]
Level 23 - Marquis [4 lvl]
Level 24 - Marquis [5 lvl]
Level 25 - Marquis [6 lvl]
Level 26 - Marquis [7 lvl]
Level 27 - Marquis [8 lvl]
Level 28 - Marquis [9 lvl]
Level 29 - Marquis [10 lvl]
level 30 - Count

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jo3-l** [comment]
To my knowledge, at present, the leveling system does not include the role reward in its level-up message; rather, it only mentions the new level. As such, I'm not too sure what to make of your request -- would you mind clarifying what exactly you're proposing? Thanks.

**Comment by jo3-l** [comment]
Closing as stale. Happy to reopen if you clarify your request per my previous reply.
