### ISSUE TITLE
bug: PR  template, broken URLs

### ISSUE THREAD

**Issue by MatiasMFM2001** [yagpdb-cc/yagpdb-cc#265]
### Expected behaviour

Hyperlinks should get me to [`CONTRIBUTING.md`](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/CONTRIBUTING.md) and [`WRITING-DOCUMENTATION.md`](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/WRITING-DOCUMENTATION.md) webpages

### Actual behaviour

Instead, an empty webpage with a "Not Found" error is shown, in both cases

### Steps to reproduce.

1. Create a PR
2. When at "Comparing <destination>...<source>" website (the place you normally use to describe the changes your PR makes), click "Preview"
3. Click the hyperlinks under "Status" section
4. You will see the error page

### Additional context

This was tested on my main PC:
- Debian 10, x86_64, fully up-to-date according to `apt`
- Mozilla Firefox `91.8.0esr (64-bit)`
- Google Chrome `100.0.4896.127 (64-bit official build)`

And using this GitHub account (I was opening PR #264)

### Terms

- [X] I agree to follow this project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
PR welcome. Fix is to change relative links in https://github.com/yagpdb-cc/yagpdb-cc/blob/master/.github/PULL_REQUEST_TEMPLATE.md to absolute links.

**Comment by MatiasMFM2001** [comment]
Great! I'll try to fix it now
