### ISSUE TITLE
Help Request: Message triggered by inactivity

### ISSUE THREAD

**Issue by moshem1234** [yagpdb-cc/yagpdb-cc#277]
So I'm experimenting with different custom command options and I was wondering if there was a way to make a message get triggered if a channel is left inactive for a said amount of time. Would this be something doable?

**Comment by lemm-e** [comment]
This should be doable with the use of `scheduleUniqueCC` used along with a Regex trigger allowing the inactivity response to be delayed each time a new message is posted. This repository however isn't the right place to ask questions regarding any such thing. Please do so on the [support server](https://discord.gg/0vYlUK2XBKldPSMY). Thanks

**Comment by l-zeuch** [comment]
Closing as NIH.
