### ISSUE TITLE
request: role

### ISSUE THREAD

**Issue by chinwiabdellkabir** [yagpdb-cc/yagpdb-cc#300]
### Description

reward system to the counter.

### Solution

please upgrade the counting code to add/remove role automatically as a last counter reward 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by l-zeuch** [comment]
There already is one such system, though it is not here and a bit more complex.

See https://github.com/BlackWolfWoof/yagpdb-cc/tree/master/Counting.

Closing, we wouldn't want to duplicate existing efforts.

**Comment by chinwiabdellkabir** [comment]
but the check mark emoji... not there so please add that option or help me with it
