### ISSUE TITLE
request: make it have the sticky message so i can actually know how to use sticky message

### ISSUE THREAD

**Issue by randomstuff69** [yagpdb-cc/yagpdb-cc#317]
### Description

IDK HOW TO USE STICKY MESSAGE

### Solution

INSTRUCTIONS STICKY MESSAGE

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by l-zeuch** [comment]
This repository does not host the *Sticky Message* template. Please
refer to the documentation hosted on the repository you got it from.

As to avoid duplicate effort, we also won't consider adding such a
template to this repository, as it is alread available at
BlackWolfWoof/yagpdb-cc[^1].

Lastly, consider not using caps lock in future issues. Thanks.

Closing as invalid / not planned.

[^1]: https://github.com/BlackWolfWoof/yagpdb-cc/blob/master/Sticky_Message/v2/README.md
