### ISSUE TITLE
bug: Believe there is an incorrect code assembly in the Set-XP/Level Command

### ISSUE THREAD

**Issue by turts121** [yagpdb-cc/yagpdb-cc#332]
### Expected behaviour

Run a -setxp or -setlevel command would change a users XP or Level. 

### Actual behaviour

Bot returned the following error message [<targetHasRoleID $user $reward>: error calling targetHasRoleID: role stack not found ]

### Steps to reproduce.

Run the script as copy and pasted from the official link [Set-XP](https://yagpdb-cc.github.io/leveling/set-xp) and setup related [Leveling Commands](https://yagpdb-cc.github.io/leveling/overview)

Proposed Solution:

Replace code from Set-XP code:

`{{- if and (ge (toInt $newLvl) (toInt $level)) (not (targetHasRoleID $user $reward)) (eq $type "stack") (ne $level "type") }} {{- giveRoleID $user $reward }}
		{{- else if and (targetHasRoleID $user $reward) (eq $type "highest") }} {{- takeRoleID $user $reward }} {{- end -}}`
			
with the following code from [Message Handler](https://yagpdb-cc.github.io/leveling/message-handler)

`{{- if and (ge (toInt $newLvl) (toInt $level)) (not (hasRoleID $reward)) (eq $type "stack") (ne $level "type") }} {{- addRoleID $reward }}
			{{- else if and (hasRoleID $reward) (eq $type "highest") $toAdd }} {{- removeRoleID $reward }} {{- end -}}`

### Terms

- [X] I agree to follow this project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by l-zeuch** [comment]
This is due to a [recent change][roles], which updated all role functions to no longer silently fail.

[roles]: https://github.com/botlabs-gg/yagpdb/commit/136b9ef3ac6a5b6f8196933d33f88eea636ed8d5

The custom command in question relied on that old behavior, thereby skipping over the `stack` value for the `targetHasRoleID` check. Instead, it should be changed such that it `continue`s or something to that effect when it encounters the first metadata key-value pair (i.e. `"type" "stack"`).

Please note, however, that your proposed change does not appear to fix this issue, and actually introduces a new kind of bug. Currently, we act upon a target user (`$user`). Your proposed fix would change that around to instead act upon the triggering user.

**Comment by l-zeuch** [comment]
I believe it should be sufficient to introduce a guard-clause at the beginning of the `range`-statement, something like this:

```go
{{ range $level, $reward := $roleRewards }}
    {{- if eq $reward "stack" }} {{ continue }} {{ end }}
    {{/* ... */}}
```

Let me know if that fixes it, after reverting your proposed change.

**Comment by l-zeuch** [comment]
/CC @jo3-l -- you're the author of this custom command. Let us know should we are missing something.

**Comment by turts121** [comment]
```
{{ if $newLvl }}
	{{ $roleRewards := sdict "type" "stack" }}
	{{ with dbGet 0 "roleRewards" }} {{ $roleRewards = sdict .Value }} {{ end }}
	{{ $type := $roleRewards.type }}
	{{ $toAdd := 0 }}
	{{ $dist := -1 }}
	{{ range $level, $reward := $roleRewards }}
    {{- if eq $type "stack" }} {{ continue }} {{ end }}
		{{- if and (le (toInt $level) (toInt $newLvl)) (or (gt $dist (sub (toInt $newLvl) (toInt $level))) (eq $dist -1)) (eq $type "highest") }}
			{{- $dist = sub (toInt $newLvl) (toInt $level) }} {{- $toAdd = $reward }}
		{{- end }}
		{{- if and (ge (toInt $newLvl) (toInt $level)) (not (targetHasRoleID $user $reward)) (eq $type "stack") (ne $level "type") }} {{- giveRoleID $user $reward }}
		{{- else if and (targetHasRoleID $user $reward) (eq $type "highest") }} {{- takeRoleID $user $reward }} {{- end -}}
	{{ end }}
	{{/* TODO: Find a better solution than removing and adding this role */}}
	{{ if $toAdd }} {{ giveRoleID $user $toAdd }} {{ end }}
{{ end }}
```

New code pasted here. This of course fixes the issue for using the `$type "stack"`, however, when using `$type "highest"` bot still returns the error
> Failed executing template: template: CC #30:54:55: executing "CC #30" at <targetHasRoleID $user $reward>: error calling targetHasRoleID: role stack not found

It will work as a temporary fix as I can set to `$type "stack"`, however it would be ideal to have `$type "highest"` work.

**Comment by l-zeuch** [comment]
Sorry, my bad.
Change the check to this instead:
```
{{- if eq $level "type" }} {{ continue }} {{ end }}
```

**Comment by turts121** [comment]
That appears to have worked! Thank you for your help. 

Code for anyone else needing to copy it quickly.

```{{ if $newLvl }}
	{{ $roleRewards := sdict "type" "stack" }}
	{{ with dbGet 0 "roleRewards" }} {{ $roleRewards = sdict .Value }} {{ end }}
	{{ $type := $roleRewards.type }}
	{{ $toAdd := 0 }}
	{{ $dist := -1 }}
	{{ range $level, $reward := $roleRewards }}
    {{- if eq $level "type" }} {{ continue }} {{ end }}
		{{- if and (le (toInt $level) (toInt $newLvl)) (or (gt $dist (sub (toInt $newLvl) (toInt $level))) (eq $dist -1)) (eq $type "highest") }}
			{{- $dist = sub (toInt $newLvl) (toInt $level) }} {{- $toAdd = $reward }}
		{{- end }}
		{{- if and (ge (toInt $newLvl) (toInt $level)) (not (targetHasRoleID $user $reward)) (eq $type "stack") (ne $level "type") }} {{- giveRoleID $user $reward }}
		{{- else if and (targetHasRoleID $user $reward) (eq $type "highest") }} {{- takeRoleID $user $reward }} {{- end -}}
	{{ end }}
	{{/* TODO: Find a better solution than removing and adding this role */}}
	{{ if $toAdd }} {{ giveRoleID $user $toAdd }} {{ end }}
{{ end }}```

**Comment by l-zeuch** [comment]
Nice!
I have to get some sleep now, but will push the appropriate changes tomorrow.

Thanks for the report!
