### ISSUE TITLE
bug: Snipe Message command broken due to Undelete command change

### ISSUE THREAD

**Issue by gandalf-potter00** [yagpdb-cc/yagpdb-cc#341]
### Expected behaviour

When running `-snipe`, it should grab the last message after running the `undelete` command and then send the appropriate information

### Actual behaviour

When running `-snipe`, it will always return "Nothing to snipe here"

### Steps to reproduce.

_Before trying these steps, make sure the snipe command is in your custom commands and enabled_
1. send a message
2. delete said message
3. run `-snipe`
4. see "Nothing to snipe here"

### Additional context

After viewing the code, the reason this errors is because of this snippet here
```
{{ $re := `\n\n\x60(\d{1,2} \w{5,7}) ago \(.{24}\)\x60 \*\*[\w.#]+\*\* \(ID (\d{17,19})\)\: ` }}
{{ $undelete := execAdmin "ud -a" }}
{{ $data := reFindAllSubmatches $re $undelete 1 }}
```
The regex is not updated to handle the new `undelete` command layout. `undelete` now uses Discord's timestamp feature, so the code will need to be modified to accomodate for this change.

### Terms

- [X] I agree to follow this project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by l-zeuch** [comment]
Thanks for the report! I have pushed 3bcf26b, which fixes this issue on
my end. Please reopen this issue if the problem persists.
