### ISSUE TITLE
request: allow usage of attached images as base for meme CC

### ISSUE THREAD

**Issue by RickeyJLancaster** [yagpdb-cc/yagpdb-cc#38]
Allow the usage of Attached images as the base for the meme instead of their link. If a attachment is found the command will require only top text as arg.
Also make the Bottom Text optional, and if is not provided use **Bottom Text** as default ~~because this is a meme by itself~~

**Comment by Jo3-L** [comment]
@GenryMg, you have time to do this? If not, I can do it myself, thought I'd ask you first as you wrote the CC.

**Comment by GenryMg** [comment]
> @GenryMg, you have time to do this? If not, I can do it myself, thought I'd ask you first as you wrote the CC.

Hi Joe. I don't think I have time to do this unfortunately. I'm currently finishing up my final exams of the year in school. Sorry about that.

**Comment by Jo3-L** [comment]
@GenryMg No worries, good luck on your exams!

**Comment by DaviiD1337** [comment]
@Jo3-L I think you made this. You can close the req :).

**Comment by jo3-l** [comment]
see above

**Comment by jo3-l** [comment]
actually no this isnt implemented bruh
