### ISSUE TITLE
request: disable level up message

### ISSUE THREAD

**Issue by ShadowNight573** [yagpdb-cc/yagpdb-cc#42]
I think it should be possible to disable the leveling up message/announcement in the leveling system

**Comment by Jo3-L** [comment]
I'm planning on doing a full rewrite of the leveling system sometime in the future (don't have an ETA, but it is on my to-do list). This is a feature I'm planning to add 👍

**Comment by buthed010203** [comment]
Hmm i should really consider this for my system as well, ive got to add a couple things and im done (namely dbRank when that pr goes thru and editing the rank command to allow checking other peoples ranks)

**Comment by DaviiD1337** [comment]
Check #132

**Comment by Jo3-L** [comment]
Resolved in https://github.com/yagpdb-cc/yagpdb-cc/commit/90b61dd20337f09260e8fd32fa3d5b78e1124ca7.
