### ISSUE TITLE
request: restructure folders

### ISSUE THREAD

**Issue by buthed010203** [yagpdb-cc/yagpdb-cc#49]
Im on mobile and am lazy but you should prob move the contents of the util folder into a new "misc" folder with the birthday cmds and such rather than calling it util
Edit: i love not being able to add tags to my own issues :^)

**Comment by buthed010203** [comment]
I feel like these category names just simplify stuff esp the misc one, its not really useful when theres 300 files on the main page and having them in folders kinda helps with the clutter if you are trying to find anything else. 
![Fun, Informational, Miscellaneous, Moderation, QoL & Maintenance, Snippets, WIP](https://i-dont.go-outsi.de/a4aIKu.png)

**Comment by l-zeuch** [comment]
Not quite sure, but this seems resolved to me?? 
@jo3-l what do you think? Closing or still WIP?

**Comment by jo3-l** [comment]
Main issue for me was `maintenance` vs `util` which has been resolved. Feel free to close.

**Comment by l-zeuch** [comment]
Closing then :^)
