### ISSUE TITLE
request: website for browsing CCs

### ISSUE THREAD

**Issue by buthed010203** [yagpdb-cc/yagpdb-cc#52]
I feel like maybe trying to use github pages might just be the way to go here

**Comment by Jo3-L** [comment]
Thought of that, but I'm shit with frontend 😄 I can give it a try though.

**Comment by buthed010203** [comment]
hehe its simple to make a terrible website that half works, if i can do it i think basically anyone can lol ![](https://xenon.is-ne.at/bIJYj2.png)

**Comment by EsenDR** [comment]
So as a thought of making a simple static site for YAG CCs, As @l-zeuch said in #186, I think something like [Jykell](https://jekyllrb.com/) is enough to suffice. If we really wanted, we can use something like [Docusaurus V2](https://docusaurus.io/), [Hugo](https://gohugo.io/), or something similar.
I have used all three mentioned above before so I do understand my way around them, just depends on who else is willing to help out. Not a huge fan of Hugo, but if everyone wants that, I'm cool with it. My knowledge is mostly based around using Docusaurus as that's what my site is based on.

**Comment by l-zeuch** [comment]
I'd be willing to help as well, myself working with Jekyll - Which, as I just recently found out, also allows for some JavaScript, if we'd ever want to use it.
Docusaurus v2 sounds interesting as well, I just don't know my way around it, should be easy to pick up though.

**Comment by EsenDR** [comment]
> I'd be willing to help as well, myself working with Jekyll - Which, as I just recently found out, also allows for some JavaScript, if we'd ever want to use it.
> Docusaurus v2 sounds interesting as well, I just don't know my way around it, should be easy to pick up though.

I definitely picked up Docusaurus quicker than Jekyll. It depends on what you guys are cool with running! Let's see what Joe has to say maybe. Otherwise you or another staff can start on the site to get started with contributing to that.

**Comment by jo3-l** [comment]
Either is fine.

**Comment by l-zeuch** [comment]
Closing, this is now a thing thanks to @EsenDR
