### ISSUE TITLE
request: subfolders for individual commands

### ISSUE THREAD

**Issue by buthed010203** [yagpdb-cc/yagpdb-cc#53]
Rather than changing all the commands to MD files (#40) why not make an individual subfolder for each one with a README file? Seems like its the best of both worlds and it only adds 1 click, its clean and could remove the comments at the top of the files entirely. It would probably make it easier to navigate as well considering there are already some commands that have their own folders.

**Comment by Jo3-L** [comment]
Thoughts on this?
![image](https://user-images.githubusercontent.com/56809242/87590628-f2906000-c69b-11ea-8715-b9f43c9212c3.png)

**Comment by buthed010203** [comment]
Would rather remove the code section at the bottom and keep it as 2 different files

**Comment by Satty9361** [comment]
Might be a good solution tbh. Top comment often confuses users.

**Comment by thewilloftheshadow** [comment]
If there's a confirmation on how these should be styled (all on one MD, two files in subfolder, etc), I'd be willing to put in some time to converting and creating these

**Comment by Jo3-L** [comment]
@thewilloftheshadow Here's an example of a command `README.md` file - [see here](https://gist.github.com/Jo3-L/dc727291bdf2d6c4e8c30a8bd47027ba).

The folder structure would be like this:
```
category-name
    ├───command-name
    │       cc-name.cc.go
    │       cc-name.minified.go
    │       README.md
    │
    └───other-command-name
            cc-name.cc.go
            cc-name.minified.go
            README.md
```

Basically, there'll be several categories of CCs, within those categories there might be subcategories for systems (like `fun/leveling`, etc.) and within those there'll be subfolders for each command.

Category names:
- `fun`: Fun commands
- `utility`: Useful tools that aren't informational
- `information`: Tools that display information
- `moderation`: Moderation commands
- `snippets`: Snippets to be included in other code
- `misc`: Anything else that doesn't fit

**Comment by thewilloftheshadow** [comment]
[First command done](https://github.com/thewilloftheshadow/yagpdb-cc/tree/reorganization1/information/avatar), look good? @Jo3-L

**Comment by Jo3-L** [comment]
@thewilloftheshadow Structure looks great! Though, if you don't mind, please change all `^` in regex triggers to `\A` instead - I never got to changing those when I found out the difference 😄

**Comment by victornpb** [comment]
> @thewilloftheshadow Structure looks great! Though, if you don't mind, please change all `^` in regex triggers to `\A` instead - I never got to changing those when I found out the difference 😄

whats the difference?😰

**Comment by jo3-l** [comment]
YAGPDB templates use the multiline mode for regex, which changes the behaviour of `^` and `$` to match the start and end of *line* respectively rather than the start and end of string. `\A` and `\z` on the other hand always match the start and end of string no matter what.

In other words, this regex `^-suggest` may match on the following:
```
Here's an example of how to make a suggestion:
-suggest hello
```
...while `\A-support` will not match.

**Comment by jo3-l** [comment]
This seems to no longer be applicable now that the website is up.
