### ISSUE TITLE
request: analytics for last week server activity

### ISSUE THREAD

**Issue by Sasiko** [yagpdb-cc/yagpdb-cc#87]
With the introduction of server insight and the partnership requirement, people will look many ways to improve their member retention. 
One idea   would be a recap which encourages the member to revisit the server once in a while. 

Recap of last week could be 
Which ch had most message
Which message had most reaction(serve great purpose for starboard with categorization as most popular image, or/and most controversial message)

which voice channel had most activity?

**Comment by Jo3-L** [comment]
This would be VERY heavy on database.. not sure if this is feasible but will keep it open for now.

**Comment by DaviiD1337** [comment]
Yeah it will hit the database very very very bad, I'll try to do something but ye, we will see.

**Comment by l-zeuch** [comment]
@DaviiD1337 any progress or can we close this issue?

**Comment by DaviiD1337** [comment]
Closing. Too much database needed. You can do yourself and PR.
