### ISSUE TITLE
bug: empty file for emoji-info cc

### ISSUE THREAD

**Issue by thewilloftheshadow** [yagpdb-cc/yagpdb-cc#91]
While working on #90, I noticed that there was an [empty file for an emoji command](https://github.com/Jo3-L/yagpdb-cc/commits/master/info/emoji/emoji.cc.lua), and no history attached to that file. Did that command get misplaced, or was that command never created?
There was a PR (#9) for that exact file, but it was never merged

**Comment by Jo3-L** [comment]
It was originally `.gitignore`'ed, but I intended to write that CC sometime so I unignored it. Never did have the chance, hence its current state. You can remove it now if you wish.

**Comment by Jo3-L** [comment]
Reopening as this issue actually isn't resolved, but the linked issue (#90) does close it.
